# LLM Judging Runner

Use this notebook to run judging in two modes:
- `single_row`: fast sanity check on one row
- `full_df`: run judging on the full dataframe

<div class="alert alert-block alert-info">
<b>Note:</b> This notebook was used to improve the judging code and LLM prompt, as here we could isolate the judging process.
</div>

<div class="alert alert-block alert-warning">
<b>Part 6:</b> This notebook Tackles the entire part 6 in addition to what we did in previous notebooks.
</div>

In [10]:
import os
import pandas as pd

from llm_client import get_client
from llm_judge import run_judge
import numpy as np

In [ ]:
import os
os.environ["NEBIUS_API_KEY"] = "Your_key"

## Pipeline for single row or full dataframe

In [ ]:
MODE = 'full_df'  # options: 'single_row' or 'full_df'
ROW_INDEX = 26

INPUT_EXCEL_PATH = 'data/generated/ecommerce_sheet_new.xlsx'
OUTPUT_EXCEL_FULL = 'data/generated/ecommerce_sheet_new_judged_full.xlsx'
OUTPUT_EXCEL_SINGLE = f'data/generated/ecommerce_sheet_new_judged_row_{ROW_INDEX}.xlsx'

In [4]:
results_df = pd.read_excel(INPUT_EXCEL_PATH)
client = get_client()

if MODE == 'full_df':
    judged_df, judged_full_df = run_judge(
        results_df=results_df.copy(),
        client=client,
        excel_path=OUTPUT_EXCEL_FULL,
    )
    print(f'Judged full dataframe with {len(judged_df)} rows -> {OUTPUT_EXCEL_FULL}')

elif MODE == 'single_row':
    if not (0 <= ROW_INDEX < len(results_df)):
        raise IndexError(f'ROW_INDEX={ROW_INDEX} is out of range for dataframe size {len(results_df)}')

    single_row_df = results_df.iloc[[ROW_INDEX]].copy()
    judged_df, judged_full_df = run_judge(
        results_df=single_row_df,
        client=client,
        excel_path=OUTPUT_EXCEL_SINGLE,
    )
    print(f'Judged one row (ROW_INDEX={ROW_INDEX}) -> {OUTPUT_EXCEL_SINGLE}')

else:
    raise ValueError("MODE must be either 'single_row' or 'full_df'")

Task 5: Judging:   0%|          | 0/50 [00:00<?, ?it/s]

Judged full dataframe with 50 rows -> ecommerce_sheet_new_judged_full.xlsx

In [5]:
judged_full_df

,product_name,Product_attribute_list,material,warranty,generated_description,latency_ms,input_tokens,output_tokens,fluency,grammar,...,length,grounding,latency_rating,cost_rating,final_score,fluency_explanation,grammar_explanation,tone_explanation,length_explanation,grounding_explanation
0,Apple iPhone 15 Pro,"features: A17 Pro chip, 120 Hz ProMotion displ...","titanium frame, Ceramic Shield glass",1‑year limited warranty,"Enjoy lightning-fast performance and a smooth,...",4888,462,89,good,good,...,good,good,ok,good,pass,"The description reads naturally, with a clear ...",The description is free of spelling and punctu...,"The tone is generally good, as it addresses th...",I counted 76 words in the description.,Step A: Extract required facts from SOURCE DAT...
1,Samsung Galaxy S24 Ultra,"features: 200 MP camera, S‑Pen support, 120 Hz...","Armor Aluminum frame, Gorilla Glass Victus",1‑year limited warranty,Imagine capturing life's moments in stunning d...,896,462,100,good,good,...,good,good,good,good,pass,"The description reads naturally, with a clear ...",The description is free of spelling and punctu...,"The tone is conversational and engaging, with ...",I counted 76 words in the description.,Step A: Extract required facts from SOURCE DAT...
2,Google Pixel 8 Pro,"features: Tensor G3 chip, Magic Eraser, 50 MP ...","matte glass back, aluminum frame",1‑year limited warranty,Enjoy stunning photos and effortless editing w...,568,459,65,ok,good,...,good,bad,good,good,fail,"The description reads naturally, but there's a...",There are no spelling or punctuation errors in...,"The description has a good tone, as it address...",I counted 56 words in the description.,Step A: Extract required facts from SOURCE DAT...
3,Sony WH‑1000XM5 Headphones,"features: active noise cancelling, 30 hr batte...",synthetic leather earcups,1‑year limited warranty,Imagine tuning out the world and fully immersi...,813,459,98,ok,good,...,ok,good,good,good,pass,"The description reads naturally, with a clear ...",There are no spelling or punctuation errors in...,"The description has a good tone, as it address...",I counted 76 words in the description.,Step A: required_facts = ['active noise cancel...
4,Bose QuietComfort Ultra Earbuds,"features: CustomTune sound calibration, ANC, I...",silicone ear tips,1‑year limited warranty,Enjoy your audio in total harmony with the Bos...,763,448,90,ok,good,...,ok,good,good,good,pass,"The description reads naturally, with a clear ...",There are no spelling or punctuation errors in...,"The description has a good tone, as it address...",I counted 76 words in the description.,Step A: Extract required facts from SOURCE DAT...
5,Amazon Echo Dot (5th Gen),"features: Alexa voice assistant, temperature s...",recycled fabric mesh,1‑year limited warranty,Enjoy seamless control over your smart home wi...,718,448,80,ok,good,...,good,good,good,good,pass,"The description reads naturally, but there are...",There are no spelling or punctuation errors in...,The description uses some corporate filler phr...,I counted 69 words in the description.,Step A: Extract required facts from SOURCE DAT...
6,Dell XPS 13 9310 Laptop,"features: 13.4″ FHD+ display, Intel Core i5, T...",CNC aluminum & carbon‑fiber palmrest,1‑year limited hardware warranty,Enjoy effortless productivity with the Dell XP...,844,468,97,good,good,...,ok,good,good,good,pass,"The description reads naturally, with a clear ...",The description has zero spelling or punctuati...,"The tone is professional and informative, addr...",I counted 76 words in the description.,Step A: Extract required facts from SOURCE DAT...
7,Apple MacBook Air 13″ (M3),"features: M3 chip, 18‑hour battery, 1080p came...",recycled aluminum unibody,1‑year limited warranty,Imagine enjoying 18 hours of work or play on a...,1009,462,100,ok,good,...,good,good,good,good,pass,"The description reads naturally, with a clear ...",There are no spelling or punctuation errors in...,"The description has a good tone, as it address...",I counted 76 words in the description.,Step A: Extract required facts from SOURCE DAT...
8,Microsoft Surface Pro 10,"features: Intel Core Ultra, detachable keyboar...",magnesium alloy chassis,1‑year limited warranty,Enjoy the power and flexibility of the Microso...,801,451,89,good,good,...,ok,good,good,good,pass,"The description reads naturally, with no awkwa...",There are no spelling or punctuation errors in...,"The description has a good tone, as it address...",I counted 76 words in the description.,Step A: Extract required facts from SOURCE DAT...
9,Garmin Forerunner 255,"features: multi‑band GPS, HRV status, 14‑day b...",fiber‑reinforced polymer,1‑year limited warranty,Enjoy precise tracking and insightful data wit...,911,460,105,good,good,...,ok,bad,good,good,fail,"The description reads naturally, with no awkwa...",There are no spelling or punctuation errors in...,"The description has a good tone, as it address...",I counted 76 words in the description.,Step A: Extract required facts from SOURCE DAT...
10,Fitbit Charge 6,"features: heart‑rate monitor, built‑in GPS, 7‑...",aluminum case,1‑year limited warranty,Enjoy staying on top of your health and fitnes...,809,451,91,good,good,...,good,good,good,good,pass,"The description reads naturally, with no awkwa...",There are no spelling or punctuation errors in...,"The tone is conversational and friendly, addre...",I counted 56 words in the description.,Step A: Extract required facts from SOURCE DAT...
11,GoPro HERO12 Black,"features: 5.3K60 video, HyperSmooth 6.0, water...",rugged polycarbonate,1‑year limited warranty,Capture every adventure in stunning 5.3K video...,781,458,95,good,good,...,ok,good,good,good,pass,"The description reads naturally, with no awkwa...",There are no spelling or punctuation errors in...,"The tone is conversational and engaging, with ...",I counted 76 words in the description.,Step A: Extract required facts from SOURCE DAT...
12,DJI Mini 4 Pro Drone,"features: 4K/60fps, omnidirectional obstacle s...",composite plastic,1‑year limited warranty,Capture stunning 4K footage at 60 frames per s...,765,462,77,good,good,...,good,bad,good,good,fail,"The description reads naturally, with no awkwa...",There are no spelling or punctuation errors in...,"The description has a good tone, as it address...",I counted 56 words in the description.,Step A: Extract required facts from SOURCE DAT...
13,Nintendo Switch OLED,"features: 7″ OLED screen, docked & handheld mo...",plastic chassis,1‑year limited warranty,Enjoy vibrant colors and deep blacks on the 7″...,690,451,77,good,good,...,good,good,good,good,pass,"The description reads naturally, with no awkwa...",There are no spelling or punctuation errors in...,"The description has a good tone, as it address...",I counted 56 words in the description.,Step A: Extract required facts from SOURCE DAT...
14,PlayStation 5 Slim,"features: ray tracing, haptic feedback control...",plastic shell,1‑year limited warranty,Experience next-level gaming with the PlayStat...,848,450,96,good,good,...,ok,good,good,good,pass,"The description reads naturally, with no awkwa...",There are no spelling or punctuation errors in...,"The description has a good tone, as it address...",I counted 76 words in the description.,Step A: Extract required facts from SOURCE DAT...
15,Xbox Series X,"features: 12 TFLOPS GPU, 1 TB SSD, 4K @ 120 Hz...",matte black casing,1‑year limited warranty,Experience the next level of gaming with the X...,822,462,93,good,good,...,ok,good,good,good,pass,"The description reads naturally, with a clear ...",There are no spelling or punctuation errors in...,"The description has a good tone, as it address...",I counted 76 words in the description.,Step A: Extract required facts from SOURCE DAT...
16,Instant Pot Duo 6‑Quart,"features: 7‑in‑1 multicooker, stainless steel ...",18/8 stainless steel,1‑year limited warranty,Imagine enjoying perfectly cooked meals with m...,1504,467,113,good,good,...,good,good,good,good,pass,"The description reads naturally, with no awkwa...",There are no spelling or punctuation errors in...,"The description has a good tone, as it address...",I counted 76 words in the description.,Step A: Extract required facts from SOURCE DAT...
17,Keurig K‑Supreme Plus Smart,"features: multistream extraction, BrewID, 78 o...",brushed stainless steel accents,1‑year limited warranty,Enjoy perfectly brewed coffee every time with ...,753,453,77,good,good,...,good,good,good,good,pass,"The description reads naturally, with no awkwa...",There are no spelling or punctuation errors in...,The description has a good tone. It addresses ...,I counted 56 words in the description.,Step A: Extract required facts from SOURCE DAT...
18,Vitamix 5200 Blender,"features: variable speed, 2‑hp motor, self‑cle...",BPA‑free Tritan jar,7‑year warranty,"Enjoying delicious, homemade smoothies and sou...",939,454,94,good,good,...,good,good,good,good,pass,"The description reads naturally, with a clear ...",The description has no spelling or punctuation...,"The tone is conversational and friendly, addre...",I counted 69 words in the description.,Step A: Extract required facts from SOURCE DAT...
19,Dyson V15 Detect Vacuum,"features: laser dust detection, HEPA filtratio...",polycarbonate & aluminum,2‑year parts & labor,Experience a whole new level of clean with the...,886,453,92,ok,good,...,ok,good,good,good,pass,"The description reads naturally, with a clear ...",The description is free of spelling and punctu...,The description uses a friendly and approachab...,I counted 76 words in the description.,Step A: Extract required facts from SOURCE DAT...
20,iRobot Roomba j7+,"features: PrecisionVision navigation, self‑emp...",plastic housing,1‑year limited warranty,Enjoy a truly effortless cleaning experience w...,2041,451,70,good,good,...,good,good,ok,good,pass,"The description reads naturally, with no awkwa...",There are no spelling or punctuation errors in...,"The description has a good tone, as it address...",I counted 56 words in the description.,Step A: Extract required facts from SOURCE DAT...
21,Yeti Rambler 20 oz Tumbler,"features: double‑wall vacuum insulated, MagSli...",kitchen‑grade stainless steel,5‑year warranty,Enjoy your beverages at the perfect temperatur...,811,452,88,good,good,...,ok,good,good,good,pass,"The description reads naturally, with no awkwa...",There are no spelling or punctuation errors in...,"The description has a good tone, as it address...",I counted 76 words in the description.,Step A: Extract required facts from SOURCE DAT...
22,Stanley Quencher H2.0 40 oz,"features: vacuum insulated, flow‑state lid, cu...",recycled stainless steel,lifetime warranty,Enjoy ice-cold drinks all day long with the St...,1191,455,101,good,good,...,ok,good,good,good,pass,"The description reads naturally, with no awkwa...",There are no spelling or punctuation errors in...,The description has a good tone. It addresses ...,I counted 76 words in the description.,Step A: Extract required facts from SOURCE DAT...
23,Hydro Flask 32 oz Wide Mouth,"features: TempShield insulation, Color Last po...",pro‑grade stainless steel,lifetime warranty,Enjoy your beverage at the perfect temperature...,791,447,93,good,good,...,ok,good,good,good,pass,"The description reads naturally, with no awkwa...",There are no spelling or punctuation errors in...,"The tone is conversational and friendly, addre...",I counted 76 words in the description.,Step A: Extract required facts from SOURCE DAT...
24,Contigo Autoseal West Loop 16 oz,"features: autoseal spill‑proof lid, double‑wal...",stainless steel,lifetime warranty,Enjoy your beverage wherever you go with the C...,794,449,70,good,good,...,good,good,good,good,pass,"The description reads naturally, with no awkwa...",There are no spelling or punctuation errors in...,"The tone is conversational and friendly, addre...",I counted 56 words in the description.,Step A: Extract required facts from SOURCE DAT...
25,Nike Air Zoom Pegasus 40,"features: React foam, Zoom Air units, engineer...",textile & synthetic,2‑year manufacturer warranty,"Enjoy a smooth, responsive ride with the Nike ...",648,448,74,good,good,...,ok,good,good,good,pass,"The description reads naturally, with no awkwa...",There are no spelling or punctuation errors in...,"The tone is conversational and engaging, addre...",I counted 76 words in the description.,Step A: Extract required facts from SOURCE DAT...
26,Adidas Ultraboost Light,"features: Light BOOST midsole, Primeknit+ uppe...",textile & synthetic,2‑year manufacturer warranty,Imagine feeling energized with every step. The...,987,454,77,ok,good,...,ok,bad,good,good,fail,"The description reads naturally, with a clear ...",There are no spelling or punctuation errors in...,"The description has a good tone, as it address...",I counted 76 words in the description.,Step A: Extract required facts from SOURCE DAT...
27,The North Face ThermoBall Eco Jacket,"features: synthetic ThermoBall insulation, DWR...",100% recycled nylon,lifetime warranty,Enjoy cozy warmth without the weight with The ...,768,447,75,ok,good,...,good,good,good,good,pass,"The description reads naturally, with a clear ...",The description is free of spelling and punctu...,The description avoids buzzwords and corporate...,I counted 69 words in the description.,Step A: Extract required facts from SOURCE DAT...
28,Patagonia Black Hole 32 L Backpack,"features: weather‑resistant, laptop sleeve, pa...",100% recycled polyester ripstop,lifetime warranty,Enjoy your adventures with the Patagonia Black...,854,452,96,good,good,...,ok,good,good,good,pass,"The description reads naturally, with no awkwa...",There are no spelling or punctuation errors in...,"The tone is conversational and friendly, addre...",I counted 96 words in the description.,Step A: Extract required facts from SOURCE DAT...
29,Osprey Farpoint 40,"features: stowaway harness, laptop sleeve, car...",450D recycled nylon,lifetime warranty,Traveling light just got easier with the Ospre...,919,449,103,good,good,...,ok,ok,good,good,pass,"The description reads naturally, with a clear ...",The description has zero spelling or punctuati...,"The description has a good tone, as it address...",I counted 76 words in the description.,Step A: Extract required facts from SOURCE DAT...
30,LEGO Star Wars Millennium Falcon 75192,"features: 7 541 pieces, detailed interior, min...",ABS plastic bricks,lifetime replacement of missing bricks,"Imagine building the iconic Millennium Falcon,...",3839,458,76,ok,good,...,good,good,ok,good,pass,"The description reads naturally, with a clear ...",The description is free of spelling and punctu...,"The description has a good tone, as it address...",I counted 76 words in the description.,Step A: Extract required facts from SOURCE DAT...
31,LEGO Icons Botanical Orchid 10311,"features: 608 pieces, adjustable blooms, decor...",ABS plastic bricks,lifetime replacement of missing bricks,Imagine the beauty of a fresh orchid gracing y...,764,453,82,good,good,...,ok,bad,good,good,fail,"The description reads naturally, with a clear ...",The description has no spelling or punctuation...,The description has a GOOD signal by addressin...,I counted 76 words in the description.,Step A: Extract required facts from SOURCE DAT...
32,Kindle Paperwhite 11th Gen,"features: 6.8″ glare‑free display, 10‑week bat...",recycled plastic,1‑year limited warranty,Imagine getting lost in a captivating story fo...,920,459,100,ok,good,...,ok,ok,good,good,fail,"The description reads naturally, with a clear ...",The description is free of spelling and punctu...,"The description has a good tone, as it address...",I counted 76 words in the description.,Step A: Extract required facts from SOURCE DAT...
33,Kobo Libra 2,"features: 7″ E Ink Carta, Bluetooth audiobooks...",plastic chassis,1‑year limited warranty,Enjoy countless hours immersed in your favorit...,1193,450,111,good,good,...,ok,good,good,good,pass,"The description reads naturally, with a clear ...",The description contains no spelling or punctu...,The description has a good tone. It addresses ...,I counted 76 words in the description.,Step A: Extract required facts from SOURCE DAT...
34,Anker Soundcore Motion+ Speaker,"features: 30 W audio, Hi‑Res, IPX7 waterproof;...",aluminum grille,18‑month warranty,"Enjoy rich, detailed audio wherever you go wit...",988,450,106,good,good,...,ok,good,good,good,pass,"The description reads naturally, with no awkwa...",There are no spelling or punctuation errors in...,The description has a good tone. It addresses ...,I counted 76 words in the description.,Step A: Extract required facts from SOURCE DAT...
35,Sonos Move 2,"features: WiFi & Bluetooth, 24‑hr battery, aut...",shock‑resistant shell,1‑year limited warranty,"Imagine enjoying your favorite music anywhere,...",1110,456,90,good,good,...,ok,bad,good,good,fail,"The description reads naturally, with a clear ...",The description is free of spelling and punctu...,The description addresses the customer directl...,I counted 76 words in the description.,Step A: Extract required facts from SOURCE DAT...
36,Philips Hue White & Color Ambiance Starter Kit,"features: 16 million colors, Bluetooth & Zigbe...",plastic bulbs,2‑year limited warranty,Imagine setting the mood with 16 million color...,884,453,97,ok,good,...,ok,good,good,good,pass,"The description reads naturally, with a clear ...",There are no spelling or punctuation errors in...,"The tone is engaging and conversational, with ...",I counted 76 words in the description.,Step A: Extract required facts from SOURCE DAT...
37,TP‑Link Deco XE75 Mesh WiFi 6E,"features: tri‑band AXE5400, 3‑pack covers 7 20...",plastic,2‑year limited warranty,Enjoy seamless WiFi throughout your entire hom...,934,469,100,ok,good,...,ok,bad,good,good,fail,"The description reads naturally, but there are...",There are no spelling or punctuation errors in...,"The description uses some GOOD signals, such a...",I counted 76 words in the description.,Step A: Extract required facts from SOURCE DAT...
38,Eufy Video Doorbell Dual,"features: dual camera, package detection, 2K r...",plastic housing,1‑year limited warranty,See everything happening at your front door wi...,919,450,108,good,good,...,good,good,good,good,pass,"The description reads naturally, with a clear ...",The description is free of spelling and punctu...,The tone is conversational and customer-focuse...,"I counted 76 words, which falls within the 50-...",Step A: Extract required facts from SOURCE DAT...
39,Blink Outdoor 4,"features: 1080p HD, 2‑year battery, weather‑re...",plastic,1‑year limited warranty,"Enjoy clear, detailed footage of your home wit...",2428,450,87,good,good,...,good,good,ok,good,pass,"The description reads naturally, with no awkwa...",There are no spelling or punctuation errors in...,The description has a good tone. It addresses ...,I counted 69 words in the description.,Step A: Extract required facts from SOURCE DAT...
40,Corsair K100 RGB Keyboard,"features: Cherry MX Speed, 4000 Hz polling, al...",brushed aluminum,2‑year warranty,Enjoy lightning-fast responsiveness with the C...,1077,452,77,good,good,...,good,good,good,good,pass,"The description reads naturally, with no awkwa...",There are no spelling or punctuation errors in...,"The description has a good tone, as it address...",I counted 69 words in the description.,Step A: Extract required facts from SOURCE DAT...
41,Logitech MX Master 3S,"features: 8K DPI sensor, MagSpeed scroll, Bolt...",plastic,1‑year limited warranty,Enjoy effortless control with the Logitech MX ...,2396,450,77,good,good,...,ok,good,ok,good,pass,"The description reads naturally, with no awkwa...",There are no spelling or punctuation errors in...,"The description has a good tone, as it address...",I counted 76 words in the description.,Step A: Extract required facts from SOURCE DAT...

***

In [6]:
judged_full_df.to_excel(f'ecommerce_sheet_new_judged_full.xlsx')

In [16]:
judged_full_df.to_excel(f'ecommerce_sheet_new_judged_row_{ROW_INDEX}_full.xlsx', index=False)

## Grounding-specific judge

In [5]:
from llm_judge import judge_one_metric
from tqdm.auto import tqdm


# Choose one metric to run separately: 'fluency', 'grammar', 'tone', 'grounding'
SPECIFIC_METRIC = "grounding"
client = get_client()

# Use judged_full_df if available, otherwise fallback to results_df
base_df = pd.read_excel(INPUT_EXCEL_PATH) 

df_separate = base_df.copy()
verdict_col = f"{SPECIFIC_METRIC}_separate_verdict"
explanation_col = f"{SPECIFIC_METRIC}_separate_explanation"

df_separate[verdict_col] = ""
df_separate[explanation_col] = ""

for idx, row in tqdm(df_separate.iterrows(), total=len(df_separate)):
    metric_result = judge_one_metric(client=client, row=row, metric=SPECIFIC_METRIC)
    df_separate.at[idx, verdict_col] = metric_result.verdict
    df_separate.at[idx, explanation_col] = metric_result.explanation

output_path = f"ecommerce_sheet_new_{SPECIFIC_METRIC}_separate.xlsx"
df_separate.to_excel(output_path, index=False)
print(f"Saved separate metric results to: {output_path}")

df_separate.head()

  0%|          | 0/50 [00:00<?, ?it/s]

Saved separate metric results to: ecommerce_sheet_new_grounding_separate.xlsx

,product_name,Product_attribute_list,material,warranty,generated_description,latency_ms,input_tokens,output_tokens,fluency,grammar,tone,length,grounding,latency_rating,cost_rating,final_score,grounding_separate_verdict,grounding_separate_explanation
0,Apple iPhone 15 Pro,"features: A17 Pro chip, 120 Hz ProMotion displ...","titanium frame, Ceramic Shield glass",1‑year limited warranty,"Enjoy a seamless, responsive experience with t...",1165,768,98,ok,good,ok,good,bad,good,good,fail,good,Grounding evaluation for Apple iPhone 15 Pro
1,Samsung Galaxy S24 Ultra,"features: 200 MP camera, S‑Pen support, 120 Hz...","Armor Aluminum frame, Gorilla Glass Victus",1‑year limited warranty,Capture every detail with the incredible 200MP...,918,768,96,ok,good,ok,good,good,good,good,pass,good,Grounding evaluation for Samsung Galaxy S24 Ultra
2,Google Pixel 8 Pro,"features: Tensor G3 chip, Magic Eraser, 50 MP ...","matte glass back, aluminum frame",1‑year limited warranty,Imagine capturing stunning photos with a 50MP ...,715,783,80,ok,good,ok,good,ok,good,good,pass,good,Grounding evaluation for Google Pixel 8 Pro
3,Sony WH‑1000XM5 Headphones,"features: active noise cancelling, 30 hr batte...",synthetic leather earcups,1‑year limited warranty,Enjoy immersive sound experiences with the Son...,826,765,104,good,good,good,ok,good,good,good,pass,good,Grounding evaluation for Sony WH-1000XM5 Headp...
4,Bose QuietComfort Ultra Earbuds,"features: CustomTune sound calibration, ANC, I...",silicone ear tips,1‑year limited warranty,Imagine enjoying your music without any distra...,808,754,86,ok,good,ok,ok,good,good,good,pass,good,Grounding evaluation for Bose QuietComfort Ult...

## Tone-specific judge

In [ ]:
from llm_judge import judge_one_metric
from tqdm.auto import tqdm

# Choose one metric to run separately: 'fluency', 'grammar', 'tone', 'grounding'
SPECIFIC_METRIC = "tone"
client = get_client()

# Use judged_full_df if available, otherwise fallback to results_df
base_df = pd.read_excel(INPUT_EXCEL_PATH) 

df_separate = base_df.copy()
verdict_col = f"{SPECIFIC_METRIC}_separate_verdict"
explanation_col = f"{SPECIFIC_METRIC}_separate_explanation"

df_separate[verdict_col] = ""
df_separate[explanation_col] = ""

for idx, row in tqdm(df_separate.iterrows(), total=len(df_separate)):
    metric_result = judge_one_metric(client=client, row=row, metric=SPECIFIC_METRIC)
    df_separate.at[idx, verdict_col] = metric_result.verdict
    df_separate.at[idx, explanation_col] = metric_result.explanation

output_path = f"ecommerce_sheet_new_{SPECIFIC_METRIC}_separate.xlsx"

  0%|          | 0/50 [00:00<?, ?it/s]

PermissionError: [Errno 13] Permission denied: 'ecommerce_sheet_new_tone_separate.xlsx'

In [ ]:
df_separate.to_excel(output_path, index=False)
print(f"Saved separate metric results to: {output_path}")

Saved separate metric results to: ecommerce_sheet_new_tone_separate.xlsx

In [6]:
df_separate.head()

,product_name,Product_attribute_list,material,warranty,generated_description,latency_ms,input_tokens,output_tokens,fluency,grammar,tone,length,grounding,latency_rating,cost_rating,final_score,tone_separate_verdict,tone_separate_explanation
0,Apple iPhone 15 Pro,"features: A17 Pro chip, 120 Hz ProMotion displ...","titanium frame, Ceramic Shield glass",1‑year limited warranty,"Enjoy a seamless, responsive experience with t...",1165,768,98,ok,good,ok,good,bad,good,good,fail,ok,The description uses buzz words ('seamless') a...
1,Samsung Galaxy S24 Ultra,"features: 200 MP camera, S‑Pen support, 120 Hz...","Armor Aluminum frame, Gorilla Glass Victus",1‑year limited warranty,Capture every detail with the incredible 200MP...,918,768,96,ok,good,ok,good,good,good,good,pass,ok,The description uses buzz words ('incredible')...
2,Google Pixel 8 Pro,"features: Tensor G3 chip, Magic Eraser, 50 MP ...","matte glass back, aluminum frame",1‑year limited warranty,Imagine capturing stunning photos with a 50MP ...,715,783,80,ok,good,ok,good,ok,good,good,pass,good,"The description uses a conversational tone, ad..."
3,Sony WH‑1000XM5 Headphones,"features: active noise cancelling, 30 hr batte...",synthetic leather earcups,1‑year limited warranty,Enjoy immersive sound experiences with the Son...,826,765,104,good,good,good,ok,good,good,good,pass,ok,The description addresses the customer directl...
4,Bose QuietComfort Ultra Earbuds,"features: CustomTune sound calibration, ANC, I...",silicone ear tips,1‑year limited warranty,Imagine enjoying your music without any distra...,808,754,86,ok,good,ok,ok,good,good,good,pass,ok,The description uses a benefit-focused opening...

## Fluency-specific judge

In [4]:
from llm_judge import judge_one_metric
from tqdm.auto import tqdm

# Choose one metric to run separately: 'fluency', 'grammar', 'tone', 'grounding'
SPECIFIC_METRIC = "fluency"
client = get_client()

# Use judged_full_df if available, otherwise fallback to results_df
base_df = pd.read_excel(INPUT_EXCEL_PATH) 

df_separate = base_df.copy()
verdict_col = f"{SPECIFIC_METRIC}_separate_verdict"
explanation_col = f"{SPECIFIC_METRIC}_separate_explanation"

df_separate[verdict_col] = ""
df_separate[explanation_col] = ""

for idx, row in tqdm(df_separate.iterrows(), total=len(df_separate)):
    metric_result = judge_one_metric(client=client, row=row, metric=SPECIFIC_METRIC)
    df_separate.at[idx, verdict_col] = metric_result.verdict
    df_separate.at[idx, explanation_col] = metric_result.explanation

output_path = f"ecommerce_sheet_new_{SPECIFIC_METRIC}_separate.xlsx"

  0%|          | 0/50 [00:00<?, ?it/s]

In [5]:
df_separate.to_excel(output_path, index=False)
print(f"Saved separate metric results to: {output_path}")

Saved separate metric results to: ecommerce_sheet_new_fluency_separate.xlsx

In [6]:
df_separate.head()

,product_name,Product_attribute_list,material,warranty,generated_description,latency_ms,input_tokens,output_tokens,fluency,grammar,tone,length,grounding,latency_rating,cost_rating,final_score,fluency_separate_verdict,fluency_separate_explanation
0,Apple iPhone 15 Pro,"features: A17 Pro chip, 120 Hz ProMotion displ...","titanium frame, Ceramic Shield glass",1‑year limited warranty,"Enjoy a seamless, responsive experience with t...",1165,768,98,ok,good,ok,good,bad,good,good,fail,good,The description reads naturally and flows well...
1,Samsung Galaxy S24 Ultra,"features: 200 MP camera, S‑Pen support, 120 Hz...","Armor Aluminum frame, Gorilla Glass Victus",1‑year limited warranty,Capture every detail with the incredible 200MP...,918,768,96,ok,good,ok,good,good,good,good,pass,good,The description reads naturally and flows well...
2,Google Pixel 8 Pro,"features: Tensor G3 chip, Magic Eraser, 50 MP ...","matte glass back, aluminum frame",1‑year limited warranty,Imagine capturing stunning photos with a 50MP ...,715,783,80,ok,good,ok,good,ok,good,good,pass,good,The description reads naturally and flows well...
3,Sony WH‑1000XM5 Headphones,"features: active noise cancelling, 30 hr batte...",synthetic leather earcups,1‑year limited warranty,Enjoy immersive sound experiences with the Son...,826,765,104,good,good,good,ok,good,good,good,pass,good,"The description flows naturally and logically,..."
4,Bose QuietComfort Ultra Earbuds,"features: CustomTune sound calibration, ANC, I...",silicone ear tips,1‑year limited warranty,Imagine enjoying your music without any distra...,808,754,86,ok,good,ok,ok,good,good,good,pass,good,The description reads naturally and flows well...

## Grammar-specific judgme

In [7]:
from llm_judge import judge_one_metric
from tqdm.auto import tqdm

# Choose one metric to run separately: 'fluency', 'grammar', 'tone', 'grounding'
SPECIFIC_METRIC = "grammar"
client = get_client()

# Use judged_full_df if available, otherwise fallback to results_df
base_df = pd.read_excel(INPUT_EXCEL_PATH) 

df_separate = base_df.copy()
verdict_col = f"{SPECIFIC_METRIC}_separate_verdict"
explanation_col = f"{SPECIFIC_METRIC}_separate_explanation"

df_separate[verdict_col] = ""
df_separate[explanation_col] = ""

for idx, row in tqdm(df_separate.iterrows(), total=len(df_separate)):
    metric_result = judge_one_metric(client=client, row=row, metric=SPECIFIC_METRIC)
    df_separate.at[idx, verdict_col] = metric_result.verdict
    df_separate.at[idx, explanation_col] = metric_result.explanation

output_path = f"ecommerce_sheet_new_{SPECIFIC_METRIC}_separate.xlsx"
df_separate.to_excel(output_path, index=False)
print(f"Saved separate metric results to: {output_path}")

  0%|          | 0/50 [00:00<?, ?it/s]

Saved separate metric results to: ecommerce_sheet_new_grammar_separate.xlsx

## Comparing multi-metric prompt to metric specific prompt and analyzing with human judgement

In [ ]:
full_df_path = 'data/generated/assignment_01_full_new.xlsx'
full_df = pd.read_excel(full_df_path)
grounding_specific_df = pd.read_excel('data/generated/ecommerce_sheet_new_grounding_separate.xlsx')
tone_specific_df = pd.read_excel('data/generated/ecommerce_sheet_new_tone_separate.xlsx')
fluency_specific_df = pd.read_excel('data/generated/ecommerce_sheet_new_fluency_separate.xlsx')
grammar_specific_df = pd.read_excel('data/generated/ecommerce_sheet_new_grammar_separate.xlsx')

In [14]:
sample_df_idx = full_df.sample(15, random_state=42).index
sample_full_df = full_df.loc[sample_df_idx]
grounding_specific_sample_df = grounding_specific_df.loc[sample_df_idx]
tone_specific_sample_df = tone_specific_df.loc[sample_df_idx]
fluency_specific_sample_df = fluency_specific_df.loc[sample_df_idx]
grammar_specific_sample_df = grammar_specific_df.loc[sample_df_idx]

In [16]:
sample_full_df

,product_name,Product_attribute_list,material,warranty,generated_description,latency_ms,input_tokens,output_tokens,fluency,grammar,...,grounding,latency_rating,cost_rating,final_score,fluency_explanation,grammar_explanation,tone_explanation,length_explanation,grounding_explanation,cost
13,Nintendo Switch OLED,"features: 7″ OLED screen, docked & handheld mo...",plastic chassis,1‑year limited warranty,Enjoy vibrant colors and stunning visuals with...,656,757,82,ok,good,...,bad,good,good,fail,"The description reads naturally, but there are...",There are no spelling or punctuation errors in...,The description uses some corporate filler wor...,I counted 76 words in the description.,Step A: Extract required facts from SOURCE DAT...,0.000020
39,Blink Outdoor 4,"features: 1080p HD, 2‑year battery, weather‑re...",plastic,1‑year limited warranty,Enjoy crystal-clear 1080p HD video footage of ...,672,756,79,good,good,...,good,good,good,pass,"The description reads naturally, with no awkwa...",There are no spelling or punctuation errors in...,"The tone is neutral and informative, without a...",I counted 66 words in the description.,Step A: Extract required facts from SOURCE DAT...,0.000020
30,LEGO Star Wars Millennium Falcon 75192,"features: 7 541 pieces, detailed interior, min...",ABS plastic bricks,lifetime replacement of missing bricks,"Imagine building the iconic Millennium Falcon,...",1017,764,86,ok,good,...,good,good,good,pass,"The description reads naturally, with a clear ...",There are no spelling or punctuation errors in...,"The description has a good tone, as it address...",I counted 76 words in the description.,Step A: Extract required facts from SOURCE DAT...,0.000020
45,SanDisk Extreme PRO 128 GB SDXC,"features: UHS‑I U3, 200 MB/s read, waterproof;...",plastic,lifetime limited warranty,You'll enjoy capturing every moment with the S...,800,765,98,good,good,...,good,good,good,pass,"The description reads naturally, with a clear ...",The description is free of spelling and punctu...,"The description has a conversational tone, add...",I counted 76 words in the description.,Step A: Extract required facts from SOURCE DAT...,0.000021
17,Keurig K‑Supreme Plus Smart,"features: multistream extraction, BrewID, 78 o...",brushed stainless steel accents,1‑year limited warranty,"Enjoy perfectly brewed coffee, every time, wit...",811,759,84,good,good,...,good,good,good,pass,"The description reads naturally, with a clear ...",There are no spelling or punctuation errors in...,The tone of the description is conversational ...,I counted 76 words in the description.,Step A: Extract required facts from SOURCE DAT...,0.000020
48,BenQ PD2725U 27″ Monitor,"features: 4K UHD IPS, 98% P3, Thunderbolt 3; c...",metal stand,3‑year warranty,Want to experience your digital content in stu...,745,766,95,good,good,...,good,good,good,pass,"The description reads naturally, with no awkwa...",There are no spelling or punctuation errors in...,"The description has a good tone, as it address...",I counted 76 words in the description.,Step A: Extract required facts from SOURCE DAT...,0.000021
26,Adidas Ultraboost Light,"features: Light BOOST midsole, Primeknit+ uppe...",textile & synthetic,2‑year manufacturer warranty,Imagine running on clouds – that’s the feeling...,867,778,92,ok,good,...,good,good,good,pass,"The description reads naturally, with a clear ...",There are no spelling or punctuation errors in...,"The description has a good tone, as it address...",I counted 76 words in the description.,Step A: Extract required facts from SOURCE DAT...,0.000021
25,Nike Air Zoom Pegasus 40,"features: React foam, Zoom Air units, engineer...",textile & synthetic,2‑year manufacturer warranty,Experience the effortless energy return of the...,762,754,99,good,good,...,good,good,good,pass,"The description reads naturally, with no awkwa...",There are no spelling or punctuation errors in...,"The description has a good tone, as it address...",I counted 76 words in the description.,Step A: Extract required facts from SOURCE DAT...,0.000021
32,Kindle Paperwhite 11th Gen,"features: 6.8″ glare‑free display, 10‑week bat...",recycled plastic,1‑year limited warranty,Enjoy weeks of reading on a single charge with...,881,765,106,good,good,...,good,good,good,pass,"The description reads naturally, with no awkwa...",There are no spelling or punctuation errors in...,"The description has a good tone, as it address...",I counted 76 words in the description.,Step A: Extract required facts from SOURCE DAT...,0.000022
19,Dyson V15 Detect Vacuum,"features: laser dust detection, HEPA filtratio...",polycarbonate & aluminum,2‑year parts & labor,Experience the power of Dyson's laser dust det...,1025,759,118,ok,good,...,good,good,good,fail,"The description reads naturally, with a clear ...",The description is free of spelling and punctu...,"The tone is generally good, as it addresses th...",I counted 96 words in the description.,Step A: Extract required facts from SOURCE DAT...,0.000022
12,DJI Mini 4 Pro Drone,"features: 4K/60fps, omnidirectional obstacle s...",composite plastic,1‑year limited warranty,Imagine capturing stunning 4K/60fps footage fr...,823,786,108,good,good,...,good,good,good,pass,"The description reads naturally, with no awkwa...",There are no spelling or punctuation errors in...,The description has a good tone. It addresses ...,I counted 76 words in the description.,Step A: Extract required facts from SOURCE DAT...,0.000022
4,Bose QuietComfort Ultra Earbuds,"features: CustomTune sound calibration, ANC, I...",silicone ear tips,1‑year limited warranty,Imagine enjoying your music without any distra...,808,754,86,ok,good,...,good,good,good,pass,"The description reads naturally, but there are...",There are no spelling or punctuation errors in...,"The description uses some GOOD signals, such a...",I counted 76 words in the description.,Step A: Extract required facts from SOURCE DAT...,0.000020
37,TP‑Link Deco XE75 Mesh WiFi 6E,"features: tri‑band AXE5400, 3‑pack covers 7 20...",plastic,2‑year limited warranty,Enjoy seamless WiFi coverage throughout your e...,1021,775,119,ok,good,...,good,good,good,pass,"The description reads naturally, but there are...",There are no spelling or punctuation errors in...,The description uses some corporate filler phr...,I counted 76 words in the description.,Step A: Extract required facts from SOURCE DAT...,0.000023
8,Microsoft Surface Pro 10,"features: Intel Core Ultra, detachable keyboar...",magnesium alloy chassis,1‑year limited warranty,Enjoy the versatility and power of the Microso...,754,757,94,good,good,...,good,good,good,pass,"The description reads naturally, with a clear ...",The description has zero spelling or punctuati...,The description has a good tone. It addresses ...,I counted 76 words in the description.,Step A: Extract required facts from SOURCE DAT...,0.000021
3,Sony WH‑1000XM5 Headphones,"features: active noise cancelling, 30 hr batte...",synthetic leather earcups,1‑year limited warranty,Enjoy immersive sound experiences with the Son...,826,765,104,good,good,...,good,good,good,pass,"The description reads naturally, with no awkwa...",There are no spelling or punctuation errors in...,The description has a good tone. It addresses ...,I counted 76 words in the description.,Step A: Extract required facts from SOURCE DAT...,0.000022

***

### Helper function

In [ ]:
def matching_judging(
    full_df: pd.DataFrame,
    specific_df: pd.DataFrame,
    metric_name: str
) -> pd.DataFrame:
    """
    Compares the verdicts in the full_df with the verdicts in the specific_df for the given metric.
    Returns a DataFrame with the original columns plus a new column 'matching_verdict' indicating if they match.
    """
    product_name_col = 'product_name'
    generated_description_col = 'generated_description'
    verdict_col_full = f"{metric_name}"
    col_explanation_full = f"{metric_name}_explanation"
    
    verdict_col_specific = f"{metric_name}_separate_verdict"
    col_explanation_specific = f"{metric_name}_separate_explanation"
    
    comparison_df = full_df[[verdict_col_full, product_name_col, generated_description_col]].copy()
    comparison_df['specific_verdict'] = specific_df[verdict_col_specific]
    comparison_df['matching_verdict'] = comparison_df[verdict_col_full] == comparison_df['specific_verdict']
    comparison_df['full_explanation'] = full_df[col_explanation_full]
    comparison_df['specific_explanation'] = specific_df[col_explanation_specific]
    
    return comparison_df[comparison_df['matching_verdict'] == False]

In [29]:
grounding_comparison_df = matching_judging(sample_full_df, grounding_specific_sample_df, 'grounding')
tone_comparison_df = matching_judging(sample_full_df, tone_specific_sample_df, 'tone')      
fluency_comparison_df = matching_judging(sample_full_df, fluency_specific_sample_df, 'fluency')
grammar_comparison_df = matching_judging(sample_full_df, grammar_specific_sample_df, 'grammar')

***

## Grounding metric

In [30]:
from IPython.display import HTML, display
display(HTML(grounding_comparison_df[['grounding','specific_verdict', 'full_explanation', 'specific_explanation']].to_html(escape=False, index=False)))

The explanation is a bit lacking for some reason (even though the prompt is identical in the grounding part), but indeed seemless does not seem like a "hallucinated fact"

***

## Tone Metric

In [31]:
display(HTML(tone_comparison_df[['product_name','generated_description','tone','specific_verdict', 'full_explanation', 'specific_explanation']].to_html(escape=False, index=False)))

**Nintendo Switch OLED**- The specific metric prompt did better and followed the instructions and gave the correct grade, even though 'Enjoy vibrant colors' does not sound robotic to me. 1-0

**LEGO Star Wars Millennium Falcon 75192**- I agree with the multi metric prompt judge, as truly immersive really sounds too generic. for the tone specific judge it seemed good. 1-1

**SanDisk Extreme PRO 128 GB SDXC**- It seems that the multi metri prompt overfit to the generic part which is unexpected.  "'what matters most' could be seen as a bit generic", um I don't think it's that generic. 2-1

**Keurig K‑Supreme Plus Smart**- "'perfectly brewed coffee, every time'" sounds like a normal sells pitch to me, I agree with the multi metric prompt here. 2-2

**BenQ PD2725U 27″ Monitor**- Multi metric prompt missed the word "seamless". 3-2

**Adidas Ultraboost Light**- "top-quality running experience' could be seen as a slight corporate filler." I agree with the multi metric prompt here.  3-3

**Dyson V15 Detect Vacuum**- "buzz words, such as 'power' and 'long-lasting performance'" Multi metric prompt was off the mark here. 4-3

**Sony WH‑1000XM5 Headphones**- Again, multi metric prompt missed the word "seamless". 5-3

Overall, The specific tone prompt did slightly better but both judges were acceptable.

***

## Fluency Metric

In [32]:
display(HTML(fluency_comparison_df[['product_name','generated_description','fluency','specific_verdict', 'full_explanation', 'specific_explanation']].to_html(escape=False, index=False)))

**Nintendo Switch OLED**- "is a bit of a generic opening sentence." The multi metric judge shows a classic leakage from tone to fluency. agree with fluenct specific judge. 1-0

**LEGO Star Wars Millennium Falcon 75192**- I tend to agree with the multi metric prompt here, "the transition from the first sentence to the second sentence could be smoother.", indeed. 1-1

**Adidas Ultraboost Light**- I see a pattern here for the multi metric prompt, "However, the transition from the first sentence to the second could be smoother.", tend to disagree but it might be different opinions now. 2-1

**Dyson V15 Detect Vacuum**- "'You'll see dust you never knew existed', " I agree with the multi metric prompt that's an odd phrase you don't 'see' the dust. 2-2

**Bose QuietComfort Ultra Earbuds**- "'no matter where you are' which feels like a transition phrase.", multi metric prompt judge here is a bit too highbrow here. 3-2

**TP‑Link Deco XE75 Mesh WiFi 6E**- a pattern here as well the multi metric judge has a problem with the classic phrase "No matter where you are" but in this explanation, "'will keep you connected no matter where you are.' This phrase is a bit of a non-sequitur and disrupts the flow of the sentence.", I tend to agree. 3-3

Overall,I think they're equal and they did ok job.

***

## Grammar Metric

In [33]:
display(HTML(grammar_comparison_df[['product_name','generated_description','grammar','specific_verdict', 'full_explanation', 'specific_explanation']].to_html(escape=False, index=False)))

The grammar specific judge has interesting takes here that are not according to the prompt about formatting and it seemed to hallucinate in Adidas Ultraboost Light. Admittedly, the prompt for grammar judging was a bit lacking and the multi metric judge gave all the rows good in grammar (Which I don't disagree with).

***

# Summary

**Analysis** 

a. LLM-as-a-judge will cost less, can be adjusted to way tlarger scales and maintain consistency. However without using the top-tier models and in harder tasks than the one we tackled the accuracy can be lower. 
b. combination of LLM-as-a-judge combined with coding guardrails is the better approach for thousands of daily descriptions.